#!/bin/sh

# for i in 1 2 3; do echo $i; pin -t ./pintools/source/tools/Memory/obj-intel64/dcache.so -c 8 -b 32 -a 2 -- ./drystone.opt.$i.o; mv dcache.out dcache.out.drystone.opt.$i; done

for option in 0 1 2 3; do

    # echo -e "Testing\t$option\t$i/120";
    gcc -O$option -w ./drystone.c -o test && pin -t ./pintools/source/tools/Memory/obj-intel64/dcache.so -c 8 -b 32 -a 2 -- ./test;
    data=$(cat dcache.out)
	echo $data
    #l1_dcache=$(echo $data | grep -Po "Total-Misses: +[0-9]+ +\K([0-9]+\.[0-9]+)")
#	echo -e "$option\t$l1_dcache"
done
